version: '2'
services:
    wwwwwwwwwwwwww-app:
        image: wwwwwwwwwwwwww
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:sqlserver://wwwwwwwwwwwwww-mssql:1433;database=wwwwwwwwwwwwww
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    wwwwwwwwwwwwww-mssql:
        extends:
            file: mssql.yml
            service: wwwwwwwwwwwwww-mssql
